Repository Travel-Journal-for-Everyone/Travel-Journal-BackEnd, pull requests merged in 2025-03, with the labels that each got.

#11 [Feature] 소셜로그인(Kakao) 기능 개발
  src/main/java/com/traveljournal/domain/auth/controller/AuthController.java
  src/main/java/com/traveljournal/domain/auth/dto/FirstLoginRequest.java
  src/main/java/com/traveljournal/domain/auth/dto/KakaoIdTokenInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/KakaoMemberInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/KakaoTokenResponse.java
  src/main/java/com/traveljournal/domain/auth/dto/LoginCombinedResponse.java
  src/main/java/com/traveljournal/domain/auth/dto/LoginResponse.java
  src/main/java/com/traveljournal/domain/auth/service/AuthService.java
  src/main/java/com/traveljournal/domain/auth/util/KakaoClient.java
  src/main/java/com/traveljournal/domain/member/controller/MemberController.java
  src/main/java/com/traveljournal/domain/member/controller/TokenController.java
  src/main/java/com/traveljournal/domain/member/dto/MemberTokenResponse.java
  src/main/java/com/traveljournal/domain/member/dto/ReissueRequest.java
  src/main/java/com/traveljournal/domain/member/dto/ReissueResonse.java
  src/main/java/com/traveljournal/domain/member/dto/TokenInfo.java
  src/main/java/com/traveljournal/domain/member/entity/Member.java
  src/main/java/com/traveljournal/domain/member/entity/Token.java
  src/main/java/com/traveljournal/domain/member/repository/MemberRepository.java
  src/main/java/com/traveljournal/domain/member/repository/TokenRepository.java
  src/main/java/com/traveljournal/domain/member/service/MemberService.java
  src/main/java/com/traveljournal/domain/member/service/TokenService.java
  src/main/java/com/traveljournal/global/config/KakaoOAuthConfig.java
  src/main/java/com/traveljournal/global/config/RestTemplateConfig.java
  src/main/java/com/traveljournal/global/config/SecurityConfig.java
  src/main/java/com/traveljournal/global/data/ApiResponse.java
  src/main/java/com/traveljournal/global/data/ApiResult.java
  src/main/java/com/traveljournal/global/data/JwtValidateStatus.java
  src/main/java/com/traveljournal/global/exception/ExternalApiException.java
  src/main/java/com/traveljournal/global/exception/ResourceNotFoundException.java
  src/main/java/com/traveljournal/global/exception/UnauthorizedException.java
  src/main/java/com/traveljournal/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/traveljournal/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/traveljournal/global/security/service/CustomUserDetails.java
  src/main/java/com/traveljournal/global/security/service/CustomUserDetailsService.java
  src/main/java/com/traveljournal/global/security/util/SecurityUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: enhancement

#13 TJFE-91 [Refactor, Feat] 카카오 로그인 리팩토링 및 Swagger 정리
  src/main/java/com/traveljournal/domain/auth/controller/AuthController.java
  src/main/java/com/traveljournal/domain/auth/dto/FirstLoginRequest.java
  src/main/java/com/traveljournal/domain/auth/dto/LoginResponse.java
  src/main/java/com/traveljournal/domain/auth/service/AuthService.java
  src/main/java/com/traveljournal/domain/auth/service/KakaoService.java
  src/main/java/com/traveljournal/domain/auth/util/EnumUtils.java
  src/main/java/com/traveljournal/domain/auth/util/KakaoClient.java
  src/main/java/com/traveljournal/domain/member/controller/MemberController.java
  src/main/java/com/traveljournal/domain/member/controller/TokenController.java
  src/main/java/com/traveljournal/domain/member/dto/ReissueResonse.java
  src/main/java/com/traveljournal/domain/member/dto/ReissueResponse.java
  src/main/java/com/traveljournal/domain/member/entity/Member.java
  src/main/java/com/traveljournal/domain/member/repository/MemberRepository.java
  src/main/java/com/traveljournal/domain/member/service/MemberService.java
  src/main/java/com/traveljournal/global/config/SecurityConfig.java
  src/main/java/com/traveljournal/global/data/ApiResponse.java
Labels: enhancement, refactor

#15 TJFE-61 [Feature] 소셜로그인(Apple) 기능 개발
  build.gradle
  src/main/java/com/traveljournal/TravelJournalApplication.java
  src/main/java/com/traveljournal/domain/auth/controller/AuthController.java
  src/main/java/com/traveljournal/domain/auth/dto/SocialMemberInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/apple/AppleIdTokenInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/apple/AppleKeyInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/apple/AppleMemberInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/apple/ApplePublicKeyResponse.java
  src/main/java/com/traveljournal/domain/auth/dto/apple/AppleTokenResponse.java
  src/main/java/com/traveljournal/domain/auth/dto/kakao/KakaoIdTokenInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/kakao/KakaoMemberInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/kakao/KakaoTokenResponse.java
  src/main/java/com/traveljournal/domain/auth/service/AppleService.java
  src/main/java/com/traveljournal/domain/auth/service/AuthService.java
  src/main/java/com/traveljournal/domain/auth/service/KakaoService.java
  src/main/java/com/traveljournal/domain/auth/util/AppleClient.java
  src/main/java/com/traveljournal/domain/auth/util/EnumUtils.java
  src/main/java/com/traveljournal/domain/auth/util/KakaoClient.java
  src/main/java/com/traveljournal/domain/member/controller/MemberController.java
  src/main/java/com/traveljournal/domain/member/controller/TokenController.java
  src/main/java/com/traveljournal/domain/member/dto/ReissueResponse.java
  src/main/java/com/traveljournal/domain/member/service/MemberService.java
  src/main/java/com/traveljournal/global/config/FeignConfig.java
  src/main/java/com/traveljournal/global/config/SecurityConfig.java
  src/main/java/com/traveljournal/global/config/SwaggerConfig.java
  src/main/java/com/traveljournal/global/data/ResponseDto.java
  src/main/java/com/traveljournal/global/data/ResponseHandler.java
Labels: enhancement, refactor

#17 [Feature] 소셜로그인(Google) 기능 개발
  build.gradle
  src/main/java/com/traveljournal/domain/auth/controller/AuthController.java
  src/main/java/com/traveljournal/domain/auth/dto/google/GoogleIdTokenInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/google/GoogleMemberInfo.java
  src/main/java/com/traveljournal/domain/auth/dto/google/GoogleTokenResponse.java
  src/main/java/com/traveljournal/domain/auth/service/AuthService.java
  src/main/java/com/traveljournal/domain/auth/service/GoogleService.java
  src/main/java/com/traveljournal/domain/auth/util/GoogleClient.java
  src/main/java/com/traveljournal/domain/member/service/MemberService.java
  src/main/java/com/traveljournal/global/config/GoogleOAuthConfig.java
Labels: enhancement

#18 [Bug, refactor] 토큰 서명 길이 오류 및 구글 로그인 중복 리팩토링
  src/main/java/com/traveljournal/domain/auth/controller/AuthController.java
  src/main/java/com/traveljournal/domain/auth/dto/google/GoogleMemberInfo.java
  src/main/java/com/traveljournal/domain/auth/service/AppleService.java
  src/main/java/com/traveljournal/domain/auth/service/AuthService.java
  src/main/java/com/traveljournal/domain/auth/service/GoogleService.java
  src/main/java/com/traveljournal/domain/auth/service/KakaoService.java
  src/main/java/com/traveljournal/domain/member/entity/Member.java
  src/main/java/com/traveljournal/domain/member/repository/MemberRepository.java
  src/main/java/com/traveljournal/domain/member/service/MemberService.java
  src/main/java/com/traveljournal/domain/member/service/TokenService.java
  src/main/java/com/traveljournal/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/traveljournal/global/security/service/CustomUserDetails.java
  src/main/java/com/traveljournal/global/security/service/CustomUserDetailsService.java
Labels: bug, refactor
