Repository Travel-Journal-for-Everyone/Travel-Journal-BackEnd, pull requests merged in 2025-05, with the labels that each got.

#38 Auth도메인 관련 Swagger 문서 정리 & 토큰 예외처리 & Kakao, Apple, Google 예외처리
  build.gradle
  src/main/java/com/traveljournal/domain/auth/controller/AuthController.java
  src/main/java/com/traveljournal/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/com/traveljournal/domain/auth/service/AppleService.java
  src/main/java/com/traveljournal/domain/auth/service/AuthService.java
  src/main/java/com/traveljournal/domain/auth/service/GoogleService.java
  src/main/java/com/traveljournal/domain/auth/service/KakaoService.java
  src/main/java/com/traveljournal/domain/auth/util/EnumUtils.java
  src/main/java/com/traveljournal/domain/auth/util/GoogleClient.java
  src/main/java/com/traveljournal/domain/auth/util/KakaoClient.java
  src/main/java/com/traveljournal/domain/member/service/MemberService.java
  src/main/java/com/traveljournal/domain/search/controller/SearchController.java
  src/main/java/com/traveljournal/global/data/JwtValidateStatus.java
  src/main/java/com/traveljournal/global/exception/BadRequestException.java
  src/main/java/com/traveljournal/global/exception/GlobalExceptionHandler.java
  src/main/java/com/traveljournal/global/exception/MemberDeleteException.java
  src/main/java/com/traveljournal/global/exception/UserNotFoundException.java
  src/main/java/com/traveljournal/global/security/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/traveljournal/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/traveljournal/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/traveljournal/global/security/service/CustomUserDetailsService.java
  src/main/java/com/traveljournal/global/security/util/SecurityUtil.java
Labels: documentation, enhancement, refactor

#39 [Feature] follow 비공개 계정 팔로우 요청 수락 및 거절
  src/main/java/com/traveljournal/domain/member/controller/FollowController.java
  src/main/java/com/traveljournal/domain/member/dto/FollowProfileResponse.java
  src/main/java/com/traveljournal/domain/member/dto/FollowRequestResponse.java
  src/main/java/com/traveljournal/domain/member/entity/Follow.java
  src/main/java/com/traveljournal/domain/member/entity/RequestStatus.java
  src/main/java/com/traveljournal/domain/member/repository/FollowRepository.java
  src/main/java/com/traveljournal/domain/member/service/FollowService.java
  src/main/java/com/traveljournal/global/exception/FollowAccountScopeException.java
  src/main/java/com/traveljournal/global/exception/FollowBadRequestException.java
  src/main/java/com/traveljournal/global/exception/FollowNotFoundException.java
  src/main/java/com/traveljournal/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#43 [Feature] 탐험하기(여행일지) 기능 구현 #41
  src/main/java/com/traveljournal/TravelJournalApplication.java
  src/main/java/com/traveljournal/domain/explore/controller/ExploreController.java
  src/main/java/com/traveljournal/domain/explore/dto/ExploreJournalFeedResponse.java
  src/main/java/com/traveljournal/domain/explore/entity/ExploreSeenJournal.java
  src/main/java/com/traveljournal/domain/explore/repository/ExploreSeenJournalRepository.java
  src/main/java/com/traveljournal/domain/explore/service/ExploreFeedService.java
  src/main/java/com/traveljournal/domain/journal/dto/JournalIdListRequest.java
  src/main/java/com/traveljournal/domain/journal/entity/Journal.java
  src/main/java/com/traveljournal/domain/journal/repository/JournalRepository.java
  src/main/java/com/traveljournal/domain/member/entity/Member.java
  src/main/java/com/traveljournal/domain/member/repository/FollowRepository.java
  src/main/java/com/traveljournal/domain/member/service/FollowService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: enhancement

#46 [Feature] 회원 차단 기능
  src/main/java/com/traveljournal/domain/journal/repository/JournalRepository.java
  src/main/java/com/traveljournal/domain/member/controller/BlockController.java
  src/main/java/com/traveljournal/domain/member/dto/BlockResponse.java
  src/main/java/com/traveljournal/domain/member/entity/Block.java
  src/main/java/com/traveljournal/domain/member/repository/BlockRepository.java
  src/main/java/com/traveljournal/domain/member/service/BlockService.java
  src/main/java/com/traveljournal/domain/place/repository/PlaceRepository.java
  src/main/java/com/traveljournal/domain/search/controller/SearchController.java
  src/main/java/com/traveljournal/domain/search/repository/MemberSearchRepository.java
  src/main/java/com/traveljournal/domain/search/service/JournalSearchService.java
  src/main/java/com/traveljournal/domain/search/service/MemberSearchService.java
  src/main/java/com/traveljournal/domain/search/service/PlaceSearchService.java
  src/main/java/com/traveljournal/global/exception/BlockBadRequestException.java
  src/main/java/com/traveljournal/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#48 [refactor] follow-block 패키지 분리
  src/main/java/com/traveljournal/domain/block/controller/BlockController.java
  src/main/java/com/traveljournal/domain/block/dto/BlockResponse.java
  src/main/java/com/traveljournal/domain/block/entity/Block.java
  src/main/java/com/traveljournal/domain/block/repository/BlockRepository.java
  src/main/java/com/traveljournal/domain/block/service/BlockService.java
  src/main/java/com/traveljournal/domain/explore/service/ExploreFeedService.java
  src/main/java/com/traveljournal/domain/follow/controller/FollowController.java
  src/main/java/com/traveljournal/domain/follow/dto/FollowProfileResponse.java
  src/main/java/com/traveljournal/domain/follow/dto/FollowRequestResponse.java
  src/main/java/com/traveljournal/domain/follow/entity/Follow.java
  src/main/java/com/traveljournal/domain/follow/entity/RequestStatus.java
  src/main/java/com/traveljournal/domain/follow/repository/FollowRepository.java
  src/main/java/com/traveljournal/domain/follow/service/FollowService.java
  src/main/java/com/traveljournal/domain/member/entity/Member.java
  src/main/java/com/traveljournal/domain/search/service/JournalSearchService.java
  src/main/java/com/traveljournal/domain/search/service/MemberSearchService.java
  src/main/java/com/traveljournal/domain/search/service/PlaceSearchService.java
Labels: refactor

#50 [Refactor] 여행일지 랜덤 피드 오류, 구글 & 카카오 redirectURI test 기능 추가
  src/main/java/com/traveljournal/domain/auth/controller/AuthController.java
  src/main/java/com/traveljournal/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/com/traveljournal/domain/auth/service/AuthService.java
  src/main/java/com/traveljournal/domain/auth/service/GoogleService.java
  src/main/java/com/traveljournal/domain/auth/util/GoogleClient.java
  src/main/java/com/traveljournal/domain/block/controller/BlockController.java
  src/main/java/com/traveljournal/domain/block/dto/BlockResponse.java
  src/main/java/com/traveljournal/domain/explore/controller/ExploreController.java
  src/main/java/com/traveljournal/domain/explore/service/ExploreFeedService.java
  src/main/java/com/traveljournal/domain/follow/controller/FollowController.java
  src/main/java/com/traveljournal/domain/journal/config/JournalOptimizationConfig.java
  src/main/java/com/traveljournal/domain/journal/controller/JournalController.java
  src/main/java/com/traveljournal/domain/journal/entity/Journal.java
  src/main/java/com/traveljournal/domain/journal/repository/JournalRepository.java
  src/main/java/com/traveljournal/domain/member/controller/MemberController.java
  src/main/java/com/traveljournal/domain/member/controller/TokenController.java
  src/main/java/com/traveljournal/domain/memberDashboard/controller/MemberDashboardController.java
  src/main/java/com/traveljournal/domain/place/controller/PlaceController.java
  src/main/java/com/traveljournal/global/config/GoogleOAuthConfig.java
Labels: documentation, enhancement, refactor
